export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";
export const HANDLE_ITEM_SUBMIT = "HANDLE_ITEM_SUBMIT";
export const HANDLE_ITEM_TOGGLE = "HANDLE_ITEM_TOGGLE";
export const HANDLE_ITEM_DELETE = "HANDLE_ITEM_DELETE";